---
- name: Create couchdb directory
  become: yes
  file:
    path: "{{ couchdb_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: "couchdb"
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ couchdb_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Tear down existing service
  become: yes
  docker_compose:
    project_src: "{{ couchdb_dir }}"
    state: absent
    remove_volumes: yes

- name: Run docker compose
  tags: "couchdb"
  become: yes
  docker_compose:
    project_src: "{{ couchdb_dir }}"
    pull: yes
    state: present
    remove_orphans: yes

- name: Check container
  wait_for:
    host: "127.0.0.1"
    port: "{{ couchdb_port | int }}"
