# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: couchdb-twitter-harvester-01-vol-01
    vol_size: 40
  - vol_name: couchdb-twitter-harvester-02-vol-01
    vol_size: 40
  - vol_name: couchdb-twitter-harvester-03-vol-01
    vol_size: 40

# Instance
instances:
  - name: couchdb-twitter-harvester-01
    volumes: ["couchdb-twitter-harvester-01-vol-01"]
  - name: couchdb-harvester-02
    volumes: ["couchdb-twitter-harvester-02-vol-01"]
  - name: couchdb-twitter-harvester-03
    volumes: ["couchdb-twitter-harvester-03-vol-01"]

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: assignment2
instance_flavor: uom.mse.2c9g

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_https
    description: "Demo security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-api
    description: "Security group for couchdb api access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-api
    description: "Security group for couchdb api access"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-api
    description: "Security group for couchdb api access"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0

